---
- hosts: es
  remote_user: root
  tasks:
   - name: yum source configure
     copy: 
       src: /root/local.repo
       dest: /etc/yum.repos.d/local.repo
       owner: root
       group: root
       mode: 0644
   - name: install elasticsearch
     yum:
       name: java-1.8.0-openjdk,elasticsearch
       state: latest
   - name: define hosts
     copy:
       src: /etc/hosts
       dest: /etc/hosts
       owner: root
       group: root
       mode: 0644
   - name: change configure
     template:
       src: /root/cfg.yml
       dest: /etc/elasticsearch/elasticsearch.yml
       owner: root
       group: root
       mode: '0644'
     tags: change_cfg
     notify: reload elasticsearch
   - name: enable service elasticsearch
     service: 
       name: elasticsearch
       enabled: yes
  handlers: 
   - name: reload elasticsearch
     service: 
       name: elasticsearch
       state: restarted
